print('               Casa de Câmbio ')
print('-' * 50)
print('DADOS do Cliente')
print()
nome = input('Nome: ')
idade = input('Idade: ')
cpf = input('CPF: ')
telefone = input('Telefone: ')
print('-' * 30)
print('Dados do câmbio')
print()
real = float(input('Quanto você deseja trocar: R$ '))
print()
dolar = real /3,86
euro = real / 4,33
libra = real/5,10
print('Listamos alguns valores que você pode adquirir de acordo com a quantia que você deseja trocar')
print()
print('Com R$ {} você pode trocar por US$ {}'.format(real, dolar))
print('Com R$ {} você pode trocar por  €  {}'.format(real, euro))
print('com R$ {} você pode trocar por  £  {}'.format(real, libra))
print()
print('{} a Casa de Câmbio Agradece pela Preferência, Volte Sempre!'.format(nome))
print('-' * 70)
